name: SimpleTweaks
author: MSWS
version: 1.0
api-version: 1.20
main: xyz.msws.simpletweaks.SimpleTweaks
softdepend:
  - ProtocolLib
commands:
  enderchest:
    permission: simpletweaks.enderchest
    aliases:
      - ec
      - echest
    description: Opens your enderchest
    usage: /<command>